- name: Start Portal VMs
  virt:
    name: "{{ vm_name }}"
    command: start
    uri: qemu:///system
  delegate_to: "{{ target_server }}"
  remote_user: "{{ target_server_username }}"
  become: "{{ 'no' if target_server_username == 'root' else 'yes' }}"
