---
- hosts: vsd_upgrade_ha_node2:vsd_upgrade_ha_node3
  gather_facts: no
  tasks:
    - name: Allow XMPP Connections after patching Ejabberd
      include_role:
        name: common
        tasks_from: allow-xmpp-connections
      vars:
        allow_xmpp_connection: true
