---
  - hosts: nuhs[0]
    remote_user: "{{ nuh_default_username }}"
    gather_facts: no
    tasks:
      - name: "Run the setup script for HA primary"
        command: ./setup.sh
        environment:
          HNAME: "{{ hostname }}"
          HA: "y"
          MASTER: "y"
          PEERADDR: "{{ groups['nuhs'][1] }}"
          PEERPASSWORD: "{{ nuh_default_password }}"
        args:
          chdir: /opt/proxy/bin
        when:
          - nuh_sa_or_ha is match('ha')
          - inventory_hostname == groups['nuhs'][0]