---
  - hosts: nuhs[0]
    remote_user: "{{ nuh_default_username }}"
    gather_facts: no
    tasks:
      - name: Clean known_hosts of NUH's (ignoring errors)
        known_hosts:
          name: "{{ hostname }}"
          state: absent
        no_log: True
        ignore_errors: True
        remote_user: "{{ nuh_default_username }}"

      - name: Wait for NUH ssh to be ready
          include_role:
          name: common
          tasks_from: wait-for-ssh
          vars:
            ssh_host: "{{ hostname }}"
            host_username: "root"

      - name: "Run the setup script for HA primary"
        command: ./setup.sh
        environment:
          HNAME: "{{ hostname }}"
          HA: "y"
          MASTER: "y"
          PEERADDR: "{{ groups['nuhs'][1] }}"
          PEERPASSWORD: "{{ nuh_default_password }}"
        args:
          chdir: /opt/proxy/bin
        when:
          - nuh_sa_or_ha is match('ha')