---
  - hosts: nuhs[1]
    gather_facts: no
    pre_tasks:
      - name: Set fact for nuage upgrade
        set_fact:
          nuage_upgrade: true

      - name: Check if prereq satisfied for upgrade
        include_role:
          name: common
          tasks_from: check-upgrade-prereq

      - name: Check if NUH prereq satisfied for predeploy
        include_role:
          name: common
          tasks_from: check-predeploy-prereq
    roles:
      - nuh-predeploy
