---
  - hosts: nuhs[0]
    become: yes
    gather_facts: no
    tasks:
      - name: "configure primary"
        command: ansible-playbook configure.yml
        args:
          chdir: /opt/proxy/bin/ansible