- hosts: upgrade_stats_only_vsds
  gather_facts: no
  serial: 1
  tasks:
    - name: Restore stats out certificates
      copy:
        src: "{{ item }}"
        dest: "{{ tmp_dir_name }}"
        backup: no
      with_fileglob:
        - "{{ metro_backup_root }}/{{ restore_dir | default( 'backup-latest-full' ) }}/stats-out-{{ inventory_hostname }}/*"

- hosts: upgrade_stats_only_vsds
  gather_facts: no
  tasks:
    - name: Enable stats for stats-out on stats VSDs
      include_role:
        name: common
        tasks_from: vstat-enable-stats.yml
      vars:
        failover: False
      loop: "{{ groups['stats_only_vsds'] }}"
      loop_control:
        loop_var: vsd
      run_once: true
