- name: Backup stats out certificates
  import_playbook: "vsd_stats_backup.yml"

- name: Destroy old stats out VMs
  import_playbook: "vsd_stats_upgrade_destroy.yml"

- name: Run VSD Stats Out Predeploy
  import_playbook: "vsd_stats_upgrade_predeploy.yml"

- name: Run VSD Stats Out Deploy
  import_playbook: "vsd_stats_upgrade_deploy.yml"

- name: Restore stats out certificates
  import_playbook: "vsd_stats_restore.yml"
