---
  - name: "Shut down secondary NUH HA server"
    import_playbook: nuh_ha_upgrade_shutdown_2.yml

  - name: "Predeploy secondary NUH HA server"
    import_playbook: nuh_ha_upgrade_predeploy_2.yml

  - name: "Deploy secondary NUH HA server"
    import_playbook: nuh_ha_upgrade_deploy_2.yml

  - name: "Set up primary NUH HA server"
    import_playbook: nuh_ha_upgrade_setup_1.yml

  - name: "Configure primary NUH HA server"
    import_playbook: nuh_ha_upgrade_configure_1.yml

  - name: "Shut down primary NUH HA server"
    import_playbook: nuh_ha_upgrade_shutdown_1.yml

  - name: "Predeploy primary NUH HA server"
    import_playbook: nuh_ha_upgrade_predeploy_1.yml

  - name: "Deploy primary NUH HA server"
    import_playbook: nuh_ha_upgrade_deploy_1.yml
