---
  - name: "shut down secondary server"
    import_playbook: nuh_upgrade_secondary_shutdown.yml

  - name: "deploy secondary server"
    import_playbook: nuh_upgrade_secondary_deploy.yml

  - name: "set up primary server"
    import_playbook: nuh_upgrade_primary_setup.yml
    tags: primary_setup

  - name: "configure primary server"
    import_playbook: nuh_upgrade_primary_configure.yml

  - name: "shut down primary server"
    import_playbook: nuh_upgrade_primary_shutdown.yml

  - name: "deploy primary server"
    import_playbook: nuh_upgrade_primary_deploy.yml