---
  - name: "shut down secondary ha server"
    import_playbook: nuh_upgrade_secondary_shutdown.yml

  - name: "deploy secondary ha server"
    import_playbook: nuh_upgrade_secondary_deploy.yml

  - name: "set up primary ha server"
    import_playbook: nuh_upgrade_primary_setup.yml

  - name: "configure primary ha server"
    import_playbook: nuh_upgrade_primary_configure.yml

  - name: "shut down primary ha server"
    import_playbook: nuh_upgrade_primary_shutdown.yml

  - name: "deploy primary ha server"
    import_playbook: nuh_upgrade_primary_deploy.yml