---
  - name: "shut down secondary ha server"
    import_playbook: nuh_ha_upgrade_shutdown_2.yml

  - name: "deploy secondary ha server"
    import_playbook: nuh_ha_upgrade_deploy_2.yml

  - name: "set up primary ha server"
    import_playbook: nuh_ha_upgrade_setup_1.yml

  - name: "configure primary ha server"
    import_playbook: nuh_ha_upgrade_configure_1.yml

  - name: "shut down primary ha server"
    import_playbook: nuh_ha_upgrade_shutdown_1.yml

  - name: "deploy primary ha server"
    import_playbook: nuh_ha_upgrade_deploy_1.yml