- hosts: vscs
  gather_facts: no
  connection: network_cli
  collections:
  - nokia.sros
  pre_tasks:
    - name: Lets run VSC deploy hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsc_deploy
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
    - name: get the device Info
      device_info:
      register: device_info

    - name: debug the device_info var
      debug: var=device_info

 
  roles:
    - vsc-deploy
