---
- hosts: stats_only_vsds
  gather_facts: no
  roles:
    - vsd-deploy
  post_tasks:
    - name: Enable stats for stats-out on stats VSDs
      include_role:
        name: common
        tasks_from: vstat-enable-stats.yml
      vars:
        failover: False
      loop: "{{ groups['stats_only_vsds'] }}"
      loop_control:
        loop_var: vsd
      run_once: true

    - include_role:
        name: vsd-deploy
        tasks_from: vsd_security_hardening.yml
