---
- hosts: vsd_upgrade_ha_node1
  gather_facts: no
  pre_tasks:
    - name: Set vm name, upgrade and preserve vm flags
      set_fact:
        nuage_upgrade: true
        preserve_vm: true
        vm_name: "{{ vmname }}"
    - name: set vsd hosts to drop iptables rules
      set_fact:
        vsd_hosts: [vsd_upgrade_ha_node2,vsd_upgrade_ha_node3]

  roles:
    - vsd-services-stop
    - vsd-destroy
  tasks:
      - name: Allow XMPP Connections after patching Ejabberd
        include_role:
          name: common
          tasks_from: allow-xmpp-connections
        vars:
          allow_xmpp_connection: true
          apply:
            delegate_to: "{{ item }}"
          with_items:
            - vsd_upgrade_ha_node2
            - vsd_upgrade_ha_node3
