---
- hosts: stats_only_vsds
  gather_facts: no
  vars:
    stats_out_install: True
  roles:
    - vsd-deploy
  post_tasks:
    - name: Enable stats out
      include_role:
        name: enable-stats-out
        tasks_from: main

    - include_role:
        name: vsd-deploy
        tasks_from: vsd_security_hardening.yml
