---
- hosts: stats_only_vsds
  gather_facts: no
  roles:
    - vsd-deploy
  post_tasks:
    - name: Enable stats out
      include_role:
        name: enable-stats-out
        tasks_from: main

    - name: Apply inplace patch if needed 
      include_role:
        name: vsd-upgrade-inplace
        tasks_from: main.yml

    - include_role:
        name: vsd-deploy
        tasks_from: vsd_security_hardening.yml
