---
- hosts: vsd_upgrade_ha_node1
  gather_facts: no
  pre_tasks:
    - name: Set vm name, upgrade and preserve vm flags
      set_fact:
        nuage_upgrade: true
        preserve_vm: true
        vm_name: "{{ vmname }}"

  roles:
    - vsd-services-stop
    - vsd-destroy

- name: Remove iptable rules from vsd node 2 and 3
  import_playbook: remove_iptable_rule_vsd_2_3.yml
