---
# - hosts: vsds
#   gather_facts: no
#   pre_tasks:
#     - name: Set upgrade flag
#       set_fact:
#         nuage_upgrade: true

#     - name: Check if prereq satisfied for upgrade
#       include_role:
#         name: common
#         tasks_from: check-upgrade-prereq
#   vars:
#     report_filename: vsp_postupgrade_health_report_for_vsd
#     vsd_username: "{{ vsd_custom_username | default(vsd_default_username) }}"
#     vsd_password: "{{ vsd_custom_password | default(vsd_default_password) }}"
#   roles:
#     - vsd-health

- hosts: vsds
  gather_facts: no
  tasks:
    - name: Postupgrade vsds
      include_role:
        name: vsp_upgrade_health
        tasks_from: upgrade_vsd_health
      vars:
        host: vsds
        report_host: vsp
        pre_or_post: post
        role_host: vsd

# - hosts: vstats
#   gather_facts: no
#   serial: 1
#   pre_tasks:
#     - name: Set upgrade flag
#       set_fact:
#         nuage_upgrade: true

#     - name: Check if prereq satisfied for upgrade
#       include_role:
#         name: common
#         tasks_from: check-upgrade-prereq
#   vars:
#     report_filename: vstat_postupgrade_health_report
#     vstat_username: "{{ vstat_custom_username | default(vstat_default_username) }}"
#     vstat_password: "{{ vstat_custom_password | default(vstat_default_password) }}"
#   roles:
#     - vstat-health
#   remote_user: "{{ vstat_default_username }}"

- hosts: vstats
  gather_facts: no
  tasks:
    - name: Postupgrade vstats
      include_role:
        name: vsp_upgrade_health
        tasks_from: upgrade_vstat_health
      vars:
        host: vstats
        pre_or_post: post

# - hosts: vcins
#   gather_facts: no
#   serial: 1
#   pre_tasks:
#     - name: Set upgrade flag
#       set_fact:
#         nuage_upgrade: true

#     - name: Check if prereq satisfied for upgrade
#       include_role:
#         name: common
#         tasks_from: check-upgrade-prereq
#   vars:
#     report_filename: vcin_postupgrade_health_report
#     vsd_username: "{{ vsd_custom_username | default(vsd_default_username) }}"
#     vsd_password: "{{ vsd_custom_password | default(vsd_default_password) }}"
#   roles:
#     - vcin-health

- hosts: vcins
  gather_facts: no
  serial: 1
  tasks:
    - name: Postupgrade vcins
      include_role:
        name: vsp_upgrade_health
        tasks_from: upgrade_vsd_health
      vars:
        host: vcins
        report_host: vcin
        pre_or_post: post
        role_host: vcin

# - hosts: vscs
#   gather_facts: no
#   serial: 1
#   connection: local
#   pre_tasks:
#     - name: Set upgrade flag
#       set_fact:
#         nuage_upgrade: true

#     - name: Check if prereq satisfied for upgrade
#       include_role:
#         name: common
#         tasks_from: check-upgrade-prereq
#   vars:
#     report_filename: vsp_postupgrade_health_report_for_vsc
#     vsc_username: "{{ vsc_custom_username | default(vsc_default_username) }}"
#     vsc_password: "{{ vsc_custom_password | default(vsc_default_password) }}"
#   roles:
#     - vsc-health

- hosts: vscs 
  gather_facts: no
  serial: 1
  tasks:
    - name: Postupgrade vscs -- vsp report
      include_role:
        name: vsp_upgrade_health
        tasks_from: upgrade_vsc_health
      vars:
        host: vscs
        report_host: vsp
        pre_or_post: post
        role_host: vsc

# - hosts: primary_vsds
#   gather_facts: no
#   pre_tasks:
#     - name: Set upgrade flag
#       set_fact:
#         nuage_upgrade: true

#     - name: Check if prereq satisfied for upgrade
#       include_role:
#         name: common
#         tasks_from: check-upgrade-prereq
#   vars:
#     report_filename: vstat_postupgrade_health_report_for_vsd.txt
#   roles:
#     - vstat-vsd-health

- hosts: primary_vsds
  gather_facts: no
  tasks:
    - name: Postupgrade primary_vsds
      include_role:
        name: vsp_upgrade_health
        tasks_from: upgrade_health
      vars:
        host: primary_vsds
        pre_or_post: post
        role_host: vstat-vsd

# - hosts: vscs
#   gather_facts: no
#   pre_tasks:
#     - name: Set upgrade flag
#       set_fact:
#         nuage_upgrade: true

#     - name: Check if prereq satisfied for upgrade
#       include_role:
#         name: common
#         tasks_from: check-upgrade-prereq
#   vars:
#     report_filename: vstat_postupgrade_health_report_for_vsc.txt
#     vsc_username: "{{ vsc_custom_username | default(vsc_default_username) }}"
#     vsc_password: "{{ vsc_custom_password | default(vsc_default_password) }}"
#   roles:
#     - vstat-vsc-health

- hosts: vscs 
  gather_facts: no
  tasks:
    - name: Postupgrade vscs -- vstat report
      include_role:
        name: vsp_upgrade_health
        tasks_from: upgrade_vsc_health
      vars:
        host: vscs
        report_host: vstat
        pre_or_post: post
        role_host: vstat

# - hosts: vrss
#   gather_facts: no
#   pre_tasks:
#     - name: Set upgrade flag
#       set_fact:
#         nuage_upgrade: true

#     - name: Check if prereq satisfied for upgrade
#       include_role:
#         name: common
#         tasks_from: check-upgrade-prereq
#   vars:
#     report_filename: vstat_postupgrade_health_report_for_vrs.txt
#   roles:
#     - vstat-vrs-health

- hosts: vrss
  gather_facts: no
  tasks:
    - name: Postupgrade vrss
      include_role:
        name: vsp_upgrade_health
        tasks_from: upgrade_health
      vars:
        host: vrss
        pre_or_post: post
        role_host: vstat-vrs
