---
- hosts: vscs
  gather_facts: no
  collectons:
  - nokia.sros
  roles:
    - vstat-vsc-health
  vars:
    report_filename: vstat_vsc_health_report.txt
    vsc_username: "{{ vsc_custom_username | default(vsc_default_username) }}"
    vsc_password: "{{ vsc_custom_password | default(vsc_default_password) }}"

- hosts: vrss
  gather_facts: no
  collectons:
  - nokia.sros
  roles:
    - vstat-vrs-health

- hosts: vstats,data_vstats,primary_vstats
  gather_facts: no
  serial: 1
  vars:
    report_filename: vstat_health_report
    vstat_username: "{{ vstat_custom_username | default(vstat_default_username) }}"
    vstat_password: "{{ vstat_custom_password | default(vstat_default_password) }}"
  collectons:
  - nokia.sros
  roles:
    - vstat-health
  remote_user: "{{ vstat_default_username }}"

