- name: Run this once
  block:

  - name: Format VSPK auth for VSPK module
    set_fact:
      vspk_auth:
        api_username: "{{ vsd_auth.username }}"
        api_password: "{{ vsd_auth.password }}"
        api_enterprise: "{{ vsd_auth.enterprise }}"
        api_url: "{{ vsd_auth.api_url }}"
        api_version: v5_0
    no_log: "{{ lookup('env', 'METROAE_NO_LOG') or 'true' }}"

  - name: If the basic license file is defined
    block:

    - name: Apply basic license (ignoring errors)
      connection: local
      nuage_vspk:
        auth: "{{ vspk_auth }}"
        state: present
        type: License
        properties:
          license: "{{ lookup('file', vsd_license_file) }}"
      ignore_errors: yes
      no_log: "{{ lookup('env', 'METROAE_NO_LOG') or 'true' }}"
      register: vsd_license_output

    - name: Print basic license application output for debugging
      debug: var=vsd_license_output
      when: not vsd_license_output.failed or vsd_license_output.msg is search('The license already exists in the system')

    - name: Assert that the license was already present
      assert:
        that: "vsd_license_output.msg is search('The license already exists in the system')"
        msg: "The basic license was already present and could not be applied"
      when: not vsd_continue_on_license_failure 
    
    - name: Assert that the basic license application was successful
      assert:
        that: "not vsd_license_output.failed" 
        msg: "The basic license was not already present and could not be applied"
      when: not vsd_continue_on_license_failure
    
    - name: Printing Warning for license fail and continuing execution
      fail:
        msg: "The license appplication failed or the linces already exists in the system"
      ignore_errors: yes
      when: vsd_continue_on_license_failure and (vsd_license_output.failed or vsd_license_output.msg is search('The license already exists in the system'))

    when: vsd_license_file is defined

  - name: If the cluster license is defined for HA
    block:

    - name: Apply cluster license (ignoring errors)
      connection: local
      nuage_vspk:
        auth: "{{ vspk_auth }}"
        type: License
        state: present
        properties:
          license: "{{ lookup('file', vsd_cluster_license_file) }}"
      ignore_errors: yes
      no_log: "{{ lookup('env', 'METROAE_NO_LOG') or 'true' }}"
      register: vsd_cluster_license_output

    - name: Print cluster license application output for debugging
      debug: var=vsd_cluster_license_output
      when: not vsd_cluster_license_output.failed or vsd_cluster_license_output.msg is search('The license already exists in the system')

    - name: Assert that the license was already present
      assert:
        that: "vsd_cluster_license_output.msg is search('The license already exists in the system')"
        msg: "The basic license was already present and could not be applied"
      when: not vsd_continue_on_license_failure 
    
    - name: Assert that the basic license application was successful
      assert:
        that: "not vsd_cluster_license_output.failed" 
        msg: "The basic license was not already present and could not be applied"
      when: not vsd_continue_on_license_failure

    - name: Printing Warning for license fail and continuing execution
      fail:
        msg: "The license appplication failed or the linces already exists in the system"
      ignore_errors: yes
      when: vsd_continue_on_license_failure and (vsd_cluster_license_output.failed or vsd_cluster_license_output.msg is search('The license already exists in the system'))



    when:
      - vsd_cluster_license_file is defined
      - vsd_sa_or_ha is match('ha')

  run_once: true
