- name: Check if file is present
  stat:
    path: "{{ file_path }}"
  register: file_present
  delegate_to: localhost

- name: Assert that VSD license file must exist
  assert:
    that: "file_present.stat.exists"
    success_msg: "{{ success_message | default('File exists') }}: {{ file_path }}"
    fail_msg: "{{ fail_message | default('File does not exist') }}: {{ file_path }}"