---
- name: Get unzipped files dir
  set_fact:
    nuage_unzipped_files_dir: "{{ common.nuage_unzipped_files_dir }}"

- name: Replace non-relative path
  set_fact:
    nuage_unzipped_files_dir: "{{ nuage_unzipped_files_dir | regex_replace('.+?(?=metroae_data)', '/') }}"
  when: common.nuage_unzipped_files_dir | regex_search("/metroae_data/")

- name: Replace relative path
  set_fact: 
    nuage_unzipped_files_dir: "{{ '/metroae_data/' + nuage_unzipped_files_dir }}"
  when: common.nuage_unzipped_files_dir | regex_search("^[^/]")

- name: Get stats of resulting path
  stat: 
    path: "{{ nuage_unzipped_files_dir }}"
  register: sym
  ignore_errors: True

- name: Check resulting path validity
  assert:
    that:
    - sym.stat.exists
    fail_msg: "MetroAE unzipped files directory path: {{ nuage_unzipped_files_dir }} is invalid"
