- name: Check if vsd file exists
  stat:
    path: "/etc/profile.d/vsd-banner.sh"
  register: banner_file

- debug: var=banner_file

- name: Wait for VSD file to exist
  wait_for:
    path: "/etc/profile.d/vsd-banner.sh"
    timeout: 1200
  when: not banner_file.stat.exists

- name: Get the VSD version
  shell: set -o pipefail && grep -ir "VSD_VERSION=" /etc/profile.d/vsd-banner.sh | awk -F "=" '{print $2}'
  changed_when: False
  register: vsd_version
  run_once: true

- name: Clean VSD version
  set_fact:
    vsd_version_clean: "{{ vsd_version.stdout | to_nice_json }}"

- name: Get VSD major version
  set_fact:
    vsd_major_version: "{{ vsd_version_clean.split('.')[0] | replace('\"', '')}}"

- name: Set correct python location for version less than 20
  set_fact:
    python_location: "/usr/bin/python"
  when: vsd_major_version | int < 20

- name: Set correct python location for version greater than 20
  set_fact:
    python_location: "/opt/rh/rh-python36/root/usr/bin/python"
  when: vsd_major_version | int >= 20
