- name: Get the VSD version
  shell: set -o pipefail && grep -ir "VSD_VERSION=" /etc/profile.d/vsd-banner.sh | awk -F "=" '{print $2}'
  changed_when: False
  register: vsd_version
  run_once: true

- name: Clean VSD version
  set_fact:
    vsd_version_clean: "{{ vsd_version.stdout | to_nice_json }}"

- name: Get VSD major version
  set_fact:
    vsd_major_version: "{{ vsd_version_clean.split('.')[0] | replace('\"', '')}}"
