- name: Set Vcenter cluster location
  set_fact:
    vcenter_cluster_location: "{{ (vcenter.host_clusters_folder != 'NONE') | ternary (vcenter.host_clusters_folder + '/', '') }}{{ vcenter.cluster }}"

- name: Set Vcenter Folder location
  set_fact: 
    vcenter_folder: "{{ (vcenter.host_reference != 'NONE') | ternary ('/' + vcenter.host_reference, '')}}\
      {{ vcenter.vmfolder | default('') }}"

- name: Stop virtual machine
  vmware_guest:
    hostname: "{{ target_server }}"
    username: "{{ vcenter.username }}"
    password:  "{{ vcenter.password }}"
    validate_certs: "false"
    folder: "{{ vcenter_folder }}"
    cluster: "{{ vcenter_cluster_location }}"
    datacenter: "{{ vcenter.datacenter }}" 
    name: "{{ vm_name }}"
    resource_pool: "{{ (vcenter.resource_pool != 'NONE') | ternary ('/Resources/' + vcenter.resource_pool, 'Resources') }}"
    state: "poweredoff"
  delegate_to: "localhost"
  register: stop_vm

- name: Reconfigure CPU and RAM of VM
  vmware_guest:
    hostname: "{{ target_server }}"
    username: "{{ vcenter.username }}"
    password:  "{{ vcenter.password }}"
    validate_certs: "false"
    folder: "{{ vcenter_folder }}"
    cluster: "{{ vcenter_cluster_location }}"
    datacenter: "{{ vcenter.datacenter }}" 
    name: "{{ vm_name }}"
    resource_pool: "{{ (vcenter.resource_pool != 'NONE') | ternary ('/Resources/' + vcenter.resource_pool, 'Resources') }}"
    state: "present"
    hardware:
      memory_mb: "{{ component_ram }}"
      num_cpus: "{{ component_cpus }}"
    disk:
      - size_gb: "{{ component_size_gb }}"
        type: thin
  delegate_to: "localhost"
  when: component_size_gb is defined

- name: Reconfigure CPU and RAM of VM
  vmware_guest:
    hostname: "{{ target_server }}"
    username: "{{ vcenter.username }}"
    password:  "{{ vcenter.password }}"
    validate_certs: "false"
    folder: "{{ vcenter_folder }}"
    cluster: "{{ vcenter_cluster_location }}"
    datacenter: "{{ vcenter.datacenter }}" 
    name: "{{ vm_name }}"
    resource_pool: "{{ (vcenter.resource_pool != 'NONE') | ternary ('/Resources/' + vcenter.resource_pool, 'Resources') }}"
    state: "present"
    hardware:
      memory_mb: "{{ component_ram }}"
      num_cpus: "{{ component_cpus }}"
  delegate_to: "localhost"
  when: component_size_gb is not defined


- name: Power on the VM
  vmware_guest:
    hostname: "{{ target_server }}"
    username: "{{ vcenter.username }}"
    password:  "{{ vcenter.password }}"
    validate_certs: "false"
    folder: "{{ vcenter_folder }}"
    cluster: "{{ vcenter_cluster_location }}"
    datacenter: "{{ vcenter.datacenter }}" 
    name: "{{ vm_name }}"
    resource_pool: "{{ (vcenter.resource_pool != 'NONE') | ternary ('/Resources/' + vcenter.resource_pool, 'Resources') }}"
    state: poweredon
  delegate_to: "localhost"
