- name: Deploy image on VCenter
  vmware_deploy_ovf:
    hostname: "{{ target_server }}"
    username: "{{ vcenter.username | urlencode }}"
    password: "{{ vcenter.password | urlencode }}"
    ovf: "{{ image_path }}/{{ image_file_name }}"
    datastore: "{{ vcenter.datastore }}"
    cluster: "{{ vcenter.cluster }}"
    datacenter: "{{ vcenter.datacenter }}" # folder: "{{ vcenter.vmfolder | default(omit) }}"
    name: "{{ vm_name }}"
    validate_certs: false
  delegate_to: localhost
