- name: Set VSC Creds
  set_fact:
    vsc_creds:
      host: "{{ mgmt_ip }}"
      username: "{{ vsc_username|default(vsc_default_username) }}"
      password: "{{ vsc_password|default(vsc_default_password) }}"
      timeout: "{{ vsc_command_timeout_seconds }}"

- name: Wait for VSC ssh to be ready
  include_role:
    name: common
    tasks_from: wait-for-ssh-port
  vars:
    ssh_host: "{{ vsc_creds.host }}"
    ssh_password: "{{ vsc_creds.password }}"
    ssh_user: "{{ vsc_creds.username }}"
    check_login: True

- block:
  - name: Apply specified configurations
    sros_config:
      src: "{{ item }}"
      provider: "{{ vsc_creds }}"
      save: yes
    delegate_to: localhost
    loop: "{{ vsc_config_file_paths }}"
    
  when: False

- block:
  - name: Copy VSC config file to the VSC
    connection: local
    shell: >-
      sshpass -p{{ vsc_password | default(vsc_default_password) }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      {{ proxy_conf | default('') }} {{ item }} {{ vsc_username | default(vsc_default_username) }}@{{ mgmt_ip }}:
    loop: "{{ vsc_config_file_paths }}"
    when: not mgmt_ip | ipv6

  - name: Copy VSC config file to the VSC
    connection: local
    shell: >-
      sshpass -p{{ vsc_password | default(vsc_default_password) }} scp -6 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      {{ proxy_conf | default('') }} {{ item }}
      {{ vsc_username|default(vsc_default_username) }}@{{ '[' }}{{ mgmt_ip }}{{ ']' }}:
    loop: "{{ vsc_config_file_paths }}"
    when: mgmt_ip | ipv6

- name: Execute VSC basic configuration
  sros_command:
    commands:
      - exec cf1:\abc.cfg
      - admin save
    provider: "{{ vsc_creds }}"
  delegate_to: localhost

  when: true
