- block:

  - name: Ensure there are database backups within the last day (ignoring errors)
    find:
      paths: /opt/vnsportal/db-backups/
      file_type: directory
      recurse: no
      age: -1d
    register: db_backups
    ignore_errors: true

  - block:

    - name: Get disk usage percentage
      shell: df -PTh /opt/vnsportal/db-backups/ | awk '{if(NR>1)print $6}'
      register: usage_percentage

    - name: Clean usage output
      set_fact:
        usage_amount: "{{ usage_percentage|replace('%', '') }}"

    - name: Assert that there is enough disk space available for database backup
      assert:
        that: "usage_amount|int <= {{ portal_maximum_disk_usage|int }}"
        msg: "There is not enough free disk space to do a database backup."

    - name: Backup database if there are no backups
      shell: sh /etc/cron.daily/vnsportal-backup-cron

    when: db_backups.matched == 0 or (db_backups.matched == 1 and db_backups.files is search('installer'))

  - include_role:
      name: sdwan-portal-health
      tasks_from: main

  remote_user: "{{ portal_default_username }}"
