- block:

  - name: Ensure there are database backups (ignoring errors)
    find:
      paths: '/opt/vnsportal/db-backups/'
    register: db_backups
    ignore_errors: true

  - name: Backup database if there are no backups
    shell: sh /etc/cron.daily/vnsportal-backup-cron
    when:
      - db_backups.matched == 0
      - skip_portal_db_backup|default(false) != true

  when: inventory_hostname == portal1.hostname

- include_role:
    name: sdwan-portal-health
    tasks_from: main
