- name: Clean known_hosts of VSCs (ignoring errors)
  known_hosts:
    name: "{{ mgmt_ip }}"
    state: absent
  delegate_to: localhost
  no_log: True
  ignore_errors: True

- name: Check VSC Health after deployment
  import_role: name="vsc-health"
  connection: local
  vars:
    report_filename: vsc-postdeploy-health
  delegate_to: localhost

- name: Executing VSD inplace upgrade if the vsd_install_upgrade is true
  include_role:
    name: vsd-upgrade-inplace
    tasks_from: main.yml
  when: 
    - vsd_install_inplace_upgrade | default(False)
    - not nuage_upgrade | default(False)
    - vsd_version.stdout != "20.10.R4"

