- name: Copy SSH keys to VSDs
  delegate_to: localhost
  command: "ssh-copy-id {{ vsd_custom_username | default(vsd_default_username)) }}@{{ inventory_hostname }}"
  when: component_type|default("NONE") == 'vsd'

- name: Copy SSH keys to vstat
  delegate_to: localhost
  command: "ssh-copy-id {{ vstat_custom_username | default(vstat_default_username) }}@{{ inventory_hostname }}"
  when: component_type|default("NONE") == 'vstat'
