- name: Check monit summary before upgrade
  include_role:
    name: vsd-health
    tasks_from: monit_status
  vars:
    no_report: "True"
  when: not vsd_install_inplace_upgrade | default (False)

- block:

  - block:

    - name: getting migration scripts path for patch version
      include_role:
        name: common
        tasks_from: find-file.yml
      vars:
        pattern: "VSD-migration-scripts-*.iso"
        dir_name: /home/caso/nuage-images/vsd/migration

    delegate_to: localhost
    

  - name: setting fact for migration file
    set_fact:
      vsd_migration_iso_path: "{{ file_path }}"
      vsd_migration_iso_file_name: "{{ file_name }}"
  
  when: vsd_install_inplace_upgrade | default (False)

- block:

  - name: Copy VSD-migration-scripts-xxx.iso
    copy: src="{{ vsd_migration_iso_path }}/{{ vsd_migration_iso_file_name }}"
        dest=/tmp/

  - name: Create mount point on /media/CDROM
    file:
      path: /media/CDROM
      state: directory

  - name: Mount VSD-migration-scripts-xxx.iso on /media/CDROM
    command: "mount -o loop /tmp/{{ vsd_migration_iso_file_name }} /media/CDROM"  # noqa 303

  - name: Check and print what needs to be patched on VSD
    command: /media/CDROM/vsd-patch.sh -c

  - name: Run the patch
    command: /media/CDROM/vsd-patch.sh

  remote_user: "{{ vsd_username | default(vsd_default_username) }}"
  become: "{{ 'no' if vsd_username | default(vsd_default_username) == 'root' else 'yes' }}"
  vars:
    ansible_become_pass: "{{ vsd_password | default(vsd_default_password) }}"

- name: Check monit summary after upgrade
  include_role:
    name: vsd-health
    tasks_from: monit_status
  vars:
    no_report: "True"

