- name: Query facts
  action: setup
  delegate_to: localhost

- name: Clean known_hosts of VSC's (ignoring errors)
  known_hosts:
    name: "{{ mgmt_ip }}"
    state: absent
  delegate_to: localhost
  no_log: True
  ignore_errors: True

- meta: reset_connection

- name: set fact for SROS collection
    set_fact:
      ansible_user: "{{ vsc_default_username }}"
      ansible_password: "{{ vsc_default_password }}"

- name: Wait for VSC ssh to be ready
  include_role:
    name: common
    tasks_from: wait-for-ssh-port
  vars:
    ssh_host: "{{ vsc_creds.host }}"
    ssh_password: "{{ vsc_creds.password }}"
    ssh_user: "{{ vsc_creds.username }}"
    check_login: True

- name: Get output of 'show bof'
  connection: network_cli
  sros_command:
    commands:
      - show bof
  register: bof_config

- name: Create local variable with bof config in json
  set_fact:
    bof_json: "{{ bof_config.stdout[0]|show_bof_to_json }}"

- name: Get VSD deployment mode
  include_role:
    name: common
    tasks_from: vsd-node-info.yml
  vars:
    vsd_hostname: "{{ vsd_fqdn }}"

- block:
  - name: Get output of 'show system connections port 5222'
    connection: network_cli
    sros_command:
      commands:
        - show system connections port 5222
    register: vsc_sys_conn

  - name: Create local variable with vsc system connection in json
    set_fact:
      vsc_sys_conn_json: "{{ vsc_sys_conn.stdout[0]|vsc_system_connections_to_json }}"

  when: vsd_sa_or_ha is match('ha')

- name: Get output of 'show vswitch-controller xmpp-server detail'
  connection: network_cli
  sros_command:
    commands:
      - show vswitch-controller xmpp-server detail
  register: xmpp_detail
  until: xmpp_detail.stdout[0] is search('Functional') or vsd_sa_or_ha is match('sa')
  retries: 10
  delay: 30

- name: Save existing configuration on VSC
  connection: network_cli
  sros_command:
    commands:
      - bof save
      - admin save
  register: conf_save

- import_tasks: backup_vsc.yml
