- name: Wait for PORTAL VM ssh to be ready
  include_role:
    name: common
    tasks_from: wait-for-ssh
  vars:
    ssh_host: "{{ mgmt_ip }}"
    host_username: "{{ portal_default_username }}"

- block:

  - name: Check Portal endpoint health
    uri:
      url: https://localhost/vnsportal/health
      method: GET
      validate_certs: False
    no_log: "{{ lookup('env', 'METROAE_NO_LOG') or 'true' }}"
    register: curl_output
    until: curl_output.status == 200
    retries: 30
    delay: 5

  - name: Check cluster health (ignoring errors)
    shell: "/opt/vnsportal/cluster_check.sh {{ portal_database_username }} {{ portal_database_password }}"
    ignore_errors: True
    when: portal_sa_or_ha is match('ha')

  remote_user: "{{ portal_default_username }}"
