---
# Post Deploy specific Variables
vsc_creds:
  host: "{{ mgmt_ip }}"
  username: "{{ vsc_custom_username | default(vsc_default_username) }}"
  password: "{{ vsc_custom_password | default(vsc_default_password) }}"
  timeout: 180
# Timeout in seconds
retry_timeout: 300
