- name: VSP upgrade health on VSC with credentials
  hosts: "{{ host }}"
  gather_facts: no
  serial: 1
  connection: local
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: "{{ report_host }}_{{ pre_or_post }}upgrade_health_report"
    vsc_username: "{{ vsc_custom_username | default(vsc_default_username) }}"
    vsc_password: "{{ vsc_custom_password | default(vsc_default_password) }}"
  roles:
    - "{{role_host}}-health"