- name: VSP upgrade health for VSTAT with credentials
  hosts: "{{ host }}"
  gather_facts: no
  serial: 1
  pre_tasks:
    - name: Set upgrade flag
      set_fact:
        nuage_upgrade: true

    - name: Check if prereq satisfied for upgrade
      include_role:
        name: common
        tasks_from: check-upgrade-prereq
  vars:
    report_filename: "vstat_{{ pre_or_post }}upgrade_health_report"
    vstat_username: "{{ vstat_custom_username | default(vstat_default_username) }}"
    vstat_password: "{{ vstat_custom_password | default(vstat_default_password) }}"
  roles:
    - vstat-health
  remote_user: "{{ vstat_default_username }}"