- name: Updating dr.sh on Portal 1
  lineinfile:
    path: /opt/vnsportal/dr.sh
    line: "{{ item }}"
  with_items:
    - "{{ export OWNADDRESS={{ grcn1_ip }} }}"
    - "{{ export DC1={{ groups['portal_ha_node1'][0] }},{{ groups['portal_ha_node1'][1] }},{{ groups['portal_ha_node1'][2] }},{{ groups['portal_grcn_node'][0] }} }}"
