- name: SD-WAN Portal 1 bootstrap
  command: /opt/vnsportal/cluster_bootstrap.sh
  when: inventory_hostname == portal1.hostname

- name: Capture cluster bootstrap log output
  shell: docker logs --follow --until=2m vnsportal-cluster-boostrap | tee /tmp/vnsportal_cluster_bootstrap.log
  when: inventory_hostname == portal1.hostname

- name: SD-WAN Portal 2 start up
  command: /opt/vnsportal/start.sh
  when: inventory_hostname == portal2.hostname

- name: SD-WAN Portal 3 start up
  command: /opt/vnsportal/start.sh
  when: inventory_hostname == portal3.hostname

- name: SD-WAN Portal 1 start up
  command: /opt/vnsportal/start.sh
  when: inventory_hostname == portal1.hostname
