- block:

  - name: SD-WAN Portal 1 bootstrap
    command: /opt/vnsportal/cluster_bootstrap.sh

  - name: Wait for the Portal 1 bootstrap to complete
    pause:
      seconds: 120

  when: inventory_hostname == portal1.hostname

- name: SD-WAN Portal 2 start up
  command: /opt/vnsportal/start.sh
  when: inventory_hostname == portal2.hostname

- name: Wait for the Portal 2 start up to complete
  uri:
    url: https://localhost/vnsportal/health
    method: GET
    validate_certs: False
  no_log: "{{ lookup('env', 'METROAE_NO_LOG') or 'true' }}"
  register: curl_output
  until: curl_output.status == 200
  retries: 30
  delay: 5
  when: inventory_hostname == portal2.hostname

- name: SD-WAN Portal 3 start up
  command: /opt/vnsportal/start.sh
  when: inventory_hostname == portal3.hostname

- name: Wait for the Portal 3 start up to complete
  uri:
    url: https://localhost/vnsportal/health
    method: GET
    validate_certs: False
  no_log: "{{ lookup('env', 'METROAE_NO_LOG') or 'true' }}"
  register: curl_output
  until: curl_output.status == 200
  retries: 30
  delay: 5
  when: inventory_hostname == portal3.hostname

- name: SD-WAN Portal 1 start up
  command: /opt/vnsportal/start.sh
  when: inventory_hostname == portal1.hostname

- name: Wait for the Portal 1 start up to complete
  uri:
    url: https://localhost/vnsportal/health
    method: GET
    validate_certs: False
  no_log: "{{ lookup('env', 'METROAE_NO_LOG') or 'true' }}"
  register: curl_output
  until: curl_output.status == 200
  retries: 30
  delay: 5
  when: inventory_hostname == portal1.hostname
