- include_role:
    name: check-skip-target-server
  vars:
    - target_server_list: ["kvm"]

- include_role:
    name: skip-actions
  vars:
    - action: nuh_predeploy

- include_role:
    name: check-node-reachability

- import_tasks: kvm.yml
