- name: Set local variable with vmname
  set_fact:
    vm_name: "{{ vmname }}"

- include_role:
    name: check-node-running

- name: Display if skipping predeploy
  debug:
    msg:
      - "******************************************************"
      - "Skipping NUH VM creation because it is already present"
      - "******************************************************"
  when: node_running

- block:

  - name: Set fact for internal network
    set_fact:
      internal_network: "Internal"
    when: internal_bridge is defined

  - name: Configure vCenter path
    set_fact:
      vcenter_path: "{{ target_server }}/{{ vcenter.datacenter }}/host/{{ vcenter.cluster }}\
        {{ (vcenter.host_reference != 'NONE') | ternary ('/' + vcenter.host_reference | urlencode, '') }}\
        {{ (vcenter.resource_pool != 'NONE') | ternary ('/Resources/' + vcenter.resource_pool | urlencode, '') }}"

  - name: Configure ovftool command
    set_fact:
      ovftool_command: >-
        {{ vcenter_global.ovftool }}
        --acceptAllEulas
        --noSSLVerify
        --powerOn
        -dm=thin
        -ds={{ vcenter.datastore }}
        {% if hostvars[inventory_hostname].ansible_verbosity > 0 %}
        --X:logLevel=verbose
        --X:logToConsole
        {% else %}
        --machineOutput
        {% endif %}
        -n={{ vm_name }}
        --net:"Management={{ mgmt_bridge }}"
        {% if internal_bridge is defined %}
        --net:"{{ internal_network }}={{ internal_bridge }}"
        {% endif %}
        "{{ image_path }}/{{ image_file_name }}"

  - name: Deploy NUH image on vCenter
    include_role:
      name: common
      tasks_from: vcenter-deploy-image

  - name: Finding VM folder
    connection: local
    vmware_guest_find:
      hostname: "{{ target_server }}"
      username: "{{ vcenter.username }}"
      password: "{{ vcenter.password }}"
      name: "{{ vmname }}"
      validate_certs: no
    register: nuh_vm_folder

  - name: Gathering info on VM
    connection: local
    vmware_guest_info:
      hostname: "{{ target_server }}"
      username: "{{ vcenter.username }}"
      password: "{{ vcenter.password }}"
      datacenter: "{{ vcenter.datacenter }}"
      folder: "/{{ vcenter.datacenter }}{{ nuh_vm_folder['folders'][0] }}"
      name: "{{ vmname }}"
      validate_certs: no
    register: nuh_vm_facts
    retries: 60
    delay: 5
    until: nuh_vm_facts.instance.guest_tools_status == "guestToolsRunning"

  - debug: var=nuh_vm_facts verbosity=1

  - name: Get the public key for the current user
    command: cat "{{ user_ssh_pub_key }}"
    delegate_to: localhost
    register: current_user_ssh_key

  - name: Inject SSH keys into NUH
    include_role:
      name: common
      tasks_from: vcenter-inject-ssh-keys
    vars:
      vm_username: "{{ nuh_default_username }}"
      vm_password: "{{ nuh_default_password }}"

  - name: Reboot NUH VM
    connection: local
    vmware_vm_shell:
      hostname: "{{ target_server }}"
      username: "{{ vcenter.username }}"
      password: "{{ vcenter.password }}"
      datacenter: "{{ vcenter.datacenter }}"
      cluster: "{{ vcenter.cluster }}"
      validate_certs: no
      vm_id: "{{ vm_name }}"
      vm_username: "{{ nuh_default_username }}"
      vm_password: "{{ nuh_default_password }}"
      vm_shell: "/usr/sbin/reboot"

  when: not node_running
