- name: Create directory to export
  file:
    path: "{{ mount_directory_location }}/es-backup"
    mode: 0777
    state: directory

- name: Edit /etc/exports file to make an entry of directory
  shell: "echo \"{{ mount_directory_location }}/es-backup/ 10.0.0.0/8(rw,sync,no_root_squash,no_subtree_check)\" >> /etc/exports | echo \"# ES storage\" >> /etc/exports"

- name: Export the shared directories
  command: exportfs -a

- name: Check that exported content
  command: exportfs -v
  register: nfs_status

- name: Check Paramiko version
  assert:
    that: "nfs_status.stdout = '/nfs/es-backup\t10.0.0.0/8(sync,wdelay,hide,no_subtree_check,sec=sys,rw,no_root_squash,no_all_squash)'"
    msg: "Error in NFS Server Configuration in /etc/exports file(invalid entry of directory)"
