- block:

  - name: Pull facts from target server
    setup: gather_subset=!all

  - name: List the Virtual Machines on target server
    virt: command=list_vms
    register: virt_vms

  - name: Shutdown Portal VM
    virt:
      name: "{{ vm_name }}"
      state: shutdown
      uri: qemu:///system
    when: vm_name in virt_vms

  - name: Snapshot Portal VM
    shell: "virsh snapshot-create-as {{ vm_name }} --name {{ vm_name }}-snapshot-{{ ansible_date_time.iso8601 }}"
    when: not skip_portal_snapshot|default(False)

  delegate_to: "{{ target_server }}"
  remote_user: "{{ target_server_username }}"
  become: "{{ 'no' if target_server_username == 'root' else 'yes' }}"
