- name: Clean known_hosts of VSDs (ignoring errors)
  known_hosts:
    name: "{{ mgmt_ip }}"
    state: absent
  delegate_to: localhost
  no_log: True
  ignore_errors: True

- name: Check VSD Health after deployment
  include_role: name="vsd-health"
  vars:
    report_filename: vsd-postdeploy-health
    postdeploy_only: True
    skip_vsc: True
    check_vsd_license: "{{ vsd_license_file is defined }}"

- name: Executing VSD inplace upgrade if the vsd_install_upgrade is true
  include_role:
    name: vsd-upgrade-inplace
    tasks_from: main.yml
  when: 
    - vsd_install_inplace_upgrade | default(False)
    - not nuage_upgrade | default(False)
