- name: Wait for PORTAL VM ssh to be ready
  include_role:
    name: common
    tasks_from: wait-for-ssh
  vars:
    ssh_host: "{{ mgmt_ip }}"
    host_username: "{{ portal_default_username }}"

- name: Stop Portal services
  shell: /opt/vnsportal/stop.sh
  remote_user: "{{ portal_default_username }}"
