- name: Wait for PORTAL VM ssh to be ready
  include_role:
    name: common
    tasks_from: wait-for-ssh
  vars:
    ssh_host: "{{ mgmt_ip }}"
    host_username: "{{ portal_default_username }}"

- name: Stop Portal services
  shell: /opt/vnsportal/stop.sh
  remote_user: "{{ portal_default_username }}"

- block:

  - name: Get all docker container IDs
    shell: docker ps -qa
    register: all_container_ids

  - name: Stop the docker containers (ignoring errors)
    shell: "docker stop {{ item }}"
    with_items: "{{ all_container_ids.stdout_lines }}"
    ignore_errors: yes

  - name: Delete the docker containers
    shell: "docker rm {{ item }}"
    with_items: "{{ all_container_ids.stdout_lines }}"

  - block:

    - name: Get all docker image IDs
      shell: docker images -q
      register: all_image_ids

    - name: Delete the docker images
      shell: "docker rmi -f {{ item }}"
      with_items: "{{ all_image_ids.stdout_lines }}"

    - name: Delete the vnsportal directory
      shell: rm -rf /opt/vnsportal

    when: uninstall_portal|default(False)

  remote_user: "{{ portal_default_username }}"
